!bin/sh

#This is for the reg_alu block without data mem

# cleanup
rm -rf obj_dir
rm -f reg_alu_top.vcd

# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace reg_alu_top.sv --exe reg_alu_top_tb.cpp

# build C++ project via make automatically generated by Verilator
make -j -C obj_dir/ -f Vreg_alu_top.mk Vreg_alu_top

# run executable simulation file
obj_dir/Vreg_alu_top
